# Generated by Django 4.2.16 on 2026-06-01 09:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('num_av', models.CharField(max_length=100)),
                ('num_nif', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('dateValidation', models.DateField()),
                ('valeurApprouvee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AVProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('produit', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='SuiviApp.av')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Importateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('num_telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'Utilisateur')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('article', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bureauDouane', models.CharField(max_length=255)),
                ('position_tarifaire', models.CharField(max_length=255)),
                ('norme_appliquee', models.CharField(max_length=255)),
                ('mum_E', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('av_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='SuiviApp.avproduit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='av',
            name='importateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avs', to='SuiviApp.importateur'),
        ),
        migrations.CreateModel(
            name='Appurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=100)),
                ('numero_e', models.CharField(blank=True, max_length=100, null=True)),
                ('datee', models.DateField()),
                ('bureau_douane', models.CharField(max_length=255)),
                ('fob', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cif', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appurement_fob', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appurement_cif', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('poids', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appurements', to='SuiviApp.av')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
